### PR TITLE
Fetch all

### PR DESCRIPTION
**Pull request by matthewbauer**
This should resolve issue #38. I can make any changes if you see any potential issues.

### CODE REVIEW

**Comment by matthewbauer** [comment]
Reminder to self: add test cases

**Comment by philschatz** [comment]
I'm a little concerned with accidentally making too many requests. So far, octokat makes only 1 request for each call and calling something like `octo.users.fetchAll()` will kill the rate limit. Thoughts?

**Comment by LewisW** [comment]
Might also be worth increasing the default `per_page` parameter to the maximum allowed (100, I think) when using `fetchAll`.

**Comment by adjohnson916** [comment]
+1 @philschatz any chance of merging & releasing this simple but useful change?

**Comment by macaullyjamesmuir** [comment]
+1 As a GHE user this would be great since the usual rate limits don't apply.

**Comment by philschatz** [comment]
Ah, I didn't know about the lack of limits for GHE!

This PR seems to assume a Promise implementation exists so I am reluctant to merge it in.

But I did start refactoring the code a bit to make it easier to enable/disable features (like `camelCase` in the JSON and injecting hypermedia) and adding/removing verbs (like `fetchAll`) in #81

**Comment by adjohnson916** [comment]
Though it also assumes a Promise implementation, you could consider using my [promise-recurse](https://github.com/adjohnson916/promise-recurse) module, e.g.:

```js
function fetchAll (startPromise) {
  return promiseRecurse(startPromise, function (result) {
    return result.nextPage ? result.nextPage() : null
  }).then(function (results) {
    return _.flatten(results)
  })
}
```

Using that with Octokat here: https://github.com/adjohnson916/github-mirror

**Pull request closed without merging**
