### PR TITLE
special case `html_url` in url to fn conversion

### PR DESCRIPTION
**Pull request by codeimpossible**
html_url will now be parsed into htmlUrl like other fields.

### CODE REVIEW

**Comment by matthewbauer** [comment]
I think you should be able to do .html.url as is now.

**Comment by codeimpossible** [comment]
@matthewbauer yes, that does work. It doesn't look right when debugging because html becomes a function with `.url` hanging off of it as a property. `html_url` shouldn't be converted into an api call because it's not an API endpoint, it's just a link to the github page.

**Comment by matthewbauer** [comment]
Ok, sounds reasonable. It just seems awkward to have a special case for html_url.

**Comment by codeimpossible** [comment]
@matthewbauer I agree, it's not great.

**Comment by philschatz** [comment]
Would it make sense to provide all non-templated `*_url` fields as `*Url` fields in general? Like `avatar_url`?

**Comment by codeimpossible** [comment]
@philschatz ah, yep! I totally forgot to include those fields too.

**Comment by philschatz** [comment]
Closing this in favor of #50 (which converts all non-templated `*_url` fields into `*Url`)

**Pull request closed without merging**
