### PR TITLE
Add webpack support

### PR DESCRIPTION
**Pull request by BafS**
Remove errors when using octokat with webpack (client side)

``` bash
ERROR in ./~/octokat/~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'child_process' in /Users/.../node_modules/octokat/node_modules/xmlhttprequest/lib
 @ ./~/octokat/~/xmlhttprequest/lib/XMLHttpRequest.js 15:12-36

ERROR in ./~/octokat/~/xmlhttprequest/lib/XMLHttpRequest.js
Module not found: Error: Cannot resolve module 'fs' in /Users/.../node_modules/octokat/node_modules/xmlhttprequest/lib
 @ ./~/octokat/~/xmlhttprequest/lib/XMLHttpRequest.js 16:9-22
webpack: bundle is now VALID.
```

### CODE REVIEW

**Comment by philschatz** [comment]
Thanks for the Pull Request!

Would adding `browser: { xmlhttprequest: false }` also work, and not include the `xmlhttprequest/lib/XMLHttpRequest.js` file as part of the build?

I have only used `webpack` a little bit but in my quick hack (in #79) I included a stub `src/hacks/xmlhttprequest-filler.js`. Do you have any suggestions on approaches?

**Comment by BafS** [comment]
Unfortunately I can't answer to your questions. I will get back to you if I have more informations.

**Comment by philschatz** [comment]
I believe this should be resolved when #79 is merged . Hope that helps!

**Comment by pkyeck** [comment]
it's still an issue :(

**Pull request closed without merging**
