### PR TITLE
octokat.js no longer used by latest GitHub Desktop

### PR DESCRIPTION
**Pull request by gr2m**
https://github.com/desktop/desktop/blob/9d5aa6f7f41c3ed6902e5759f41877084fbef65e/app/package.json#L19

### CODE REVIEW

**Comment by gr2m** [comment]
so sorry to bring the bad news 😭

**Comment by philschatz** [comment]
Thanks for submitting this! Sorry it took so long to merge, I have been making use of the summer weather and have not spent much time on side-projects.

It was removed in https://github.com/desktop/desktop/pull/2080 but thanks to great feedback about performance issues and providing stronger type-safety from @shiftkey and @niik I started #198 (a Roadmap to simplify this library).

It should address many of the issues brought up which will likely help other `octokat` users but unfortunately it was not quick enough to keep `octokat` in GitHub Desktop 😭

**Comment by shiftkey** [comment]
@philschatz the team also has a bunch of previous experience with the GitHub API (I help maintain Octokit.net too) so doing it all manually was a bit less daunting than it might be for others. Maybe as we add more GitHub integration we'll feel the pain again. 

Keep up the good work!

**Pull request merged**
