### PR TITLE
Accept a user agent

### PR DESCRIPTION
**Pull request by joshaber**
:wave:

This lets consumers provide a custom user agent for requests.

Let me know if I need to test or document this anywhere!

### CODE REVIEW

**Comment by joshaber** [comment]
Hi 👋 Any ETA on this? Thanks!

**Comment by philschatz** [comment]
ah yep, thanks for the reminder!

**Comment by philschatz** [comment]
This feature is now in `0.8.0`

**Comment by joshaber** [comment]
Thank you! 💖

**Pull request merged**
