### PR TITLE
Compile to JS on postinstall, include that for browserify

### PR DESCRIPTION
**Pull request by tmcw**

### CODE REVIEW

**Comment by philschatz** [comment]
Thanks! I was thinking of:

1. gitignoring all `src/*.js` files
2. compiling the JS files next to the coffee files as part of `grunt release`
3. simply pointing `index.js` to `src/octokat`

That way `coffee` does not need to run during `npm install`. Would you be interested in trying that option out?

**Comment by tmcw** [comment]
I can try that out but it seems potentially flaky - `require('./src/octokat')` can potentially point at two different things depending on what kind of environment you have set up, and one of those things can be out-of-date.

**Comment by philschatz** [comment]
Can you test if browserify now works with `octokat@0.4.4`?

**Comment by tmcw** [comment]
:+1: looks like that did the trick - thanks!!

**Comment by philschatz** [comment]
Glad to help!

**Pull request closed without merging**
